---
abstract: 'Preforked Plack Handler for performance freaks'
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  HTTP::Request::Common: '0'
  Plack::Test: '0'
  Plack::Test::Suite: '0'
  Test::More: '0.98'
  Test::TCP: '2'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.2.1, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gazelle
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Gazelle:
    file: lib/Gazelle.pm
    version: '0.10'
  Plack::Handler::Gazelle:
    file: lib/Plack/Handler/Gazelle.pm
    version: '0.10'
requires:
  Guard: '0'
  Parallel::Prefork: '0'
  Plack: '0'
  Server::Starter: '0'
  Stream::Buffered: '0'
  Try::Tiny: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/kazeburo/Gazelle/issues
  homepage: https://github.com/kazeburo/Gazelle
  repository: git://github.com/kazeburo/Gazelle.git
version: '0.10'
x_authority: cpan:KAZEBURO
x_contributors:
  - 'mattn <mattn.jp@gmail.com>'
  - 'bayashi <bayashi@cpan.org>'
